### PR TITLE
Enable social cards

### LINKED ISSUE #69: Take advantage of features in Material for MkDocs v9
### Purpose
- v8.5.0 adds cool features such as social media cards and code annotations
- v9 adds improved search

### Resources
- https://squidfunk.github.io/mkdocs-material/insiders/#8000-scotch-bonnet

### PR DESCRIPTION
**Pull request by Harvir14**
I think the social cards work, but I don't know how I can test it without deploying

### Description

- Resolves #69 

Updated mkdocs.yml file to add a social card when the link to the website is shared

### Verification

- cannot figure out how to test without pulling into main and testing the actual link

### CODE REVIEW

**Comment by Harvir14** [comment]
@DFriend01 can you accept this pull request so that I can test it, since I don't think I can see if it works without the actual link to the website

**Review by DFriend01 — APPROVED** [review]

**Comment by patrick-5546** [comment]
- You need OS dependencies as well, see https://github.com/patrick-5546/notes/pull/31

**Review by patrick-5546 — CHANGES_REQUESTED** [review]
- You need OS dependencies as well, see https://github.com/patrick-5546/notes/pull/31

**Comment by patrick-5546** [comment]
Also update this to the latest version (current v9.0.4)

**Review by patrick-5546 — COMMENTED** [review]
> * You need OS dependencies as well, see [patrick-5546/notes#31](https://github.com/patrick-5546/notes/pull/31)

The changes in `README.md`, `.github/workflows/deploy-docs.yml` and `.gitignore` are also needed

**Review by patrick-5546 — APPROVED** [review]

**Pull request merged**
