### PR TITLE
added styling for base color and hover for navigation bar

### LINKED ISSUE #40: Update color scheme
### Purpose
The blue highlighting blends into the background in dark mode
image

Also the hover color doesn't match this blue
image

### Changes
- Use a brighter blue
- Update the hover color to match this blue

### Resources
- https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/

### PR DESCRIPTION
**Pull request by Harvir14**
This pull request resolves #40 .

### CODE REVIEW

**Comment by Harvir14** [comment]
The hover is also applied to all the other pages in the navigation bar, but that was intentional. I can change it so it only applies to "Reference" if that is preferred.

**Review by patrick-5546 — COMMENTED** [review]
Can you try matching the blue on this site to our Confluence, I'm curious to see how that would look

**Comment by patrick-5546** [comment]
Color looks good, can update the links to match

**Review by DFriend01 — APPROVED** [review]
The colors are great! Thanks for the good work 😄

**Pull request merged**
